import {writeFileSync,rmSync} from 'node:fs'; import path from 'node:path';
import {h2Harness,MIN,ON} from 'file:///C:/Users/ushab/.codex/worktrees/decision-ledger-foundations-h2/Argus/server/src/decision/h2/testSupport.ts';
import {h1Harness,gateInstance} from 'file:///C:/Users/ushab/.codex/worktrees/decision-ledger-foundations-h2/Argus/server/src/decision/h1/testSupport.ts';
const env={...ON,ARGUS_DECISIONS_H2_RESIDUAL_RATE:'1',ARGUS_DECISIONS_H2_PROBE_RATE:'0'};
const h=h2Harness({env}); let runnerCalls=0; const original=h.runner.run.bind(h.runner); h.runner.run=(...args)=>{runnerCalls++; return original(...args);};
const residual={question:'run.failure-cause.residual',subject:{kind:'run',runId:'run-1'},provider:'claude-cli'} as const;
for(const reason of ['unsafe-cwd','aborted']) {if(reason==='unsafe-cwd')writeFileSync(path.join(h.root,'provider-cwd','unsafe'),'x'); const ac=new AbortController(); if(reason==='aborted')ac.abort(); const result=await h.service.assess({...residual,signal:ac.signal}); console.log('SERVICE',JSON.stringify({reason,ok:result.ok,providerCalled:result.providerCalled,outcome:result.ok?result.assessment.outcome:null,cost:result.ok?result.assessment.costUsd:null,runnerCalls,spawns:h.spawns.length})); if(reason==='unsafe-cwd')rmSync(path.join(h.root,'provider-cwd','unsafe'));}
const hh=h2Harness({env});writeFileSync(path.join(hh.root,'provider-cwd','unsafe'),'x'); await hh.watcher.check();hh.clock.advance(11*MIN); const first=await hh.watcher.check(); console.log('H2',JSON.stringify({first,spawns:hh.spawns.length,results:(await hh.records()).filter(r=>r.kind==='result')}));rmSync(path.join(hh.root,'provider-cwd','unsafe'));hh.clock.advance(16*MIN);console.log('H2_AFTER_REPAIR',JSON.stringify({next:await hh.watcher.check(),spawns:hh.spawns.length}));
const h1=h1Harness();h1.world.put(gateInstance());writeFileSync(path.join(h1.root,'provider-cwd','unsafe'),'x');await h1.tick();await h1.tick();console.log('H1',JSON.stringify({spawns:h1.spawns.length,results:(await h1.records()).filter(r=>r.kind==='result'),spent:await h1.watcher.spent()}));
